// Audio files
export const MOCK_AUDIO_URL_1 = '/story-mocks/cinematic-designed-sci-fi-whoosh-transition-nexawave-228295.mp3';
export const MOCK_AUDIO_URL_2 = '/story-mocks/descent-whoosh-long-cinematic-sound-effect-405921.mp3';
export const MOCK_AUDIO_URL_3 = '/story-mocks/sound-design-elements-sfx-ps-022-302865.mp3';

// For backwards compatibility with existing code
export const MOCK_AUDIO_BASE64 = MOCK_AUDIO_URL_1;

// Mock waveform data (simulates an audio waveform)
export const mockWaveformData = Array.from({ length: 600 }, (_, i) => {
  // Create a realistic-looking waveform with varying amplitudes
  const position = i / 600;
  const envelope = Math.sin(position * Math.PI); // Fade in/out at edges
  const detail = Math.sin(i * 0.1) * 0.3 + Math.sin(i * 0.05) * 0.2;
  return Math.max(0, Math.min(1, envelope * (0.5 + detail)));
});

// Image files
export const MOCK_IMAGE_URL_1 = '/story-mocks/piano-10046998_1280.jpg';
export const MOCK_IMAGE_URL_2 = '/story-mocks/animals-10008941_1280.jpg';
export const MOCK_IMAGE_URL_3 = '/story-mocks/namibia-9992336_1280.jpg';
export const MOCK_IMAGE_URL_4 = '/story-mocks/sand-4753305_1280.jpg';
export const MOCK_IMAGE_URL_5 = '/story-mocks/rhinoceros-10074916_1280.jpg';
export const MOCK_IMAGE_URL_6 = '/story-mocks/beef-9706049_1280.jpg';
export const MOCK_IMAGE_URL_7 = '/story-mocks/meerkat-10071273_1280.png';
export const MOCK_IMAGE_URL_8 = '/story-mocks/320px-Test_sign.jpg';
export const MOCK_IMAGE_URL_9 = '/story-mocks/abstract-10055158_640.jpg';
export const MOCK_IMAGE_URL_10 = '/story-mocks/cormorant-8489010_640.jpg';
export const MOCK_IMAGE_URL_11 = '/story-mocks/img_Page_2_Image_0002.jpg';
export const MOCK_IMAGE_URL_12 = '/story-mocks/pattern-9842070_640.png';

// Video files
export const MOCK_VIDEO_URL_1 = '/story-mocks/326739_medium.mp4';

// Document files
export const MOCK_DOC_PDF_1 = '/story-mocks/science-lesson-water-cycle.pdf';
export const MOCK_DOC_DOCX_1 = '/story-mocks/biology-cell-structure.docx';
export const MOCK_DOC_DOCX_2 = '/story-mocks/science-lesson-water-cycle.docx';
export const MOCK_DOC_MD_1 = '/story-mocks/biology-cell-structure.md';
export const MOCK_DOC_MD_2 = '/story-mocks/science-lesson-water-cycle.md';

// Text files
export const MOCK_TEXT_FILE_1 = '/story-mocks/french-seasons-vocabulary.txt';
export const MOCK_TEXT_FILE_2 = '/story-mocks/japanese-lesson-photosynthesis.txt';
export const MOCK_TEXT_FILE_3 = '/story-mocks/philosophy-presocratics.txt';
export const MOCK_TEXT_FILE_4 = '/story-mocks/spanish-ar-verbs.txt';

// CSV files
export const MOCK_CSV_FILE_1 = '/story-mocks/biology-vocabulary-list.csv';
export const MOCK_CSV_FILE_2 = '/story-mocks/philosophy-questions.csv';
export const MOCK_CSV_FILE_3 = '/story-mocks/spanish-verbs-vocabulary.csv';
export const MOCK_CSV_FILE_4 = '/story-mocks/water-cycle-questions.csv';

// RTF files
export const MOCK_RTF_FILE_1 = '/story-mocks/philosophy-presocratics.rtf';

// EPUB files
export const MOCK_EPUB_FILE_1 = '/story-mocks/water-cycle-guide.epub';

// Edu LMS files
export const MOCK_GIFT_FILE_1 = '/story-mocks/spanish-quiz.gift';
export const MOCK_QTI_FILE_1 = '/story-mocks/biology-cell-quiz.qti';
export const MOCK_IMSCC_FILE_1 = '/story-mocks/japanese-grammar-course.imscc';
export const MOCK_SCORM_ZIP_FILE_1 = '/story-mocks/biology-photosynthesis-scorm.zip';

/**
 * Mock responsive image srcSet data.
 * In production, these come from processed variants in S3.
 * For Storybook, we use the same images at different "conceptual" sizes.
 */
export const MOCK_SRCSET = {
  /** Full-size image serving as all variants (no actual resizing in mocks) */
  IMAGE_1: {
    srcSet: `${MOCK_IMAGE_URL_1} 1280w, ${MOCK_IMAGE_URL_1} 640w, ${MOCK_IMAGE_URL_8} 320w`,
    sizes: '(max-width: 320px) 320px, (max-width: 640px) 640px, 1280px',
    fallbackSrc: MOCK_IMAGE_URL_1,
  },
  IMAGE_2: {
    srcSet: `${MOCK_IMAGE_URL_2} 1280w, ${MOCK_IMAGE_URL_2} 640w, ${MOCK_IMAGE_URL_10} 320w`,
    sizes: '(max-width: 320px) 320px, (max-width: 640px) 640px, 1280px',
    fallbackSrc: MOCK_IMAGE_URL_2,
  },
  IMAGE_3: {
    srcSet: `${MOCK_IMAGE_URL_3} 1280w, ${MOCK_IMAGE_URL_3} 640w, ${MOCK_IMAGE_URL_9} 320w`,
    sizes: '(max-width: 320px) 320px, (max-width: 640px) 640px, 1280px',
    fallbackSrc: MOCK_IMAGE_URL_3,
  },
};

/**
 * Mock document thumbnail URLs.
 * In production, these are WebP thumbnails generated by documentThumbnail Lambda.
 * For Storybook, we use placeholder images.
 */
export const MOCK_DOC_THUMBNAILS = {
  PDF_WATER_CYCLE: MOCK_IMAGE_URL_4,
  PDF_BIOLOGY: MOCK_IMAGE_URL_5,
  DOCX_BIOLOGY: MOCK_IMAGE_URL_6,
  DOCX_WATER_CYCLE: MOCK_IMAGE_URL_7,
  RTF_PHILOSOPHY: MOCK_IMAGE_URL_9,
  EPUB_WATER_CYCLE: MOCK_IMAGE_URL_10,
  GIFT_SPANISH: MOCK_IMAGE_URL_11,
  QTI_BIOLOGY: MOCK_IMAGE_URL_12,
  IMSCC_JAPANESE: MOCK_IMAGE_URL_8,
};