/**
 * @fileoverview Stories for RecordingScriptPreview — the chat block that shows
 * an RS3 recording script generated by the `create_recording_script` tool, with
 * actions to save it (Word/File) or open it in Recording Studio 3.
 *
 * `getAmplifyClient()` is only invoked on the save action, so the previews
 * render without the data client.
 */

import React from "react";
import { fn } from "storybook/test";
import { Box } from "@mui/material";
import RecordingScriptPreview from "./RecordingScriptPreview";

export default {
  title: "💬 AI Assistant/Components/Recording Script Preview",
  component: RecordingScriptPreview,
  parameters: {
    layout: "padded",
    docs: {
      description: {
        component: `
# Recording Script Preview

Renders a preview of a Recording Studio 3 script produced by the AI
\`create_recording_script\` tool. Presets:

- **Conversation** — multi-speaker dialogue script
- **Vocabulary Word** — a single word with definition/pronunciation
- **Q&A Recording** — prompt/response recording script

Actions save the script as a \`Word\`/\`File\` record or open it in RS3.
        `,
      },
    },
  },
  args: {
    onOpenStudio: fn(),
    unitId: "unit-demo",
    owner: "student-demo",
    identityId: "identity-demo",
  },
  decorators: [
    (Story) => (
      <Box sx={{ maxWidth: 480 }}>
        <Story />
      </Box>
    ),
  ],
};

const conversationScript = {
  metadata: { title: "Coffee Shop Conversation", version: "1.0" },
  speakers: {
    alice: { name: "Alice", voice: "nova" },
    bob: { name: "Bob", voice: "onyx" },
  },
  dialogue: [
    { speaker: "alice", text: "Hello, how are you doing today?" },
    { speaker: "bob", text: "I'm doing well, thanks for asking." },
    { speaker: "alice", text: "Just needed a break from work." },
  ],
};

export const Conversation = {
  args: {
    toolOutput: {
      preset: "conversation",
      scriptData: conversationScript,
      lockedTracks: [],
      preview: {
        speakers: [
          { id: "alice", name: "Alice", voice: "nova" },
          { id: "bob", name: "Bob", voice: "onyx" },
        ],
        dialogueCount: 3,
        dialoguePreview: [
          { speaker: "Alice", text: "Hello, how are you doing today?" },
          { speaker: "Bob", text: "I'm doing well, thanks for asking." },
          { speaker: "Alice", text: "Just needed a break from work." },
        ],
      },
      warnings: [],
    },
  },
};

export const VocabularyWord = {
  args: {
    toolOutput: {
      preset: "word",
      scriptData: {
        metadata: { title: "こんにちは", version: "1.0" },
        speakers: {},
        dialogue: [],
      },
      wordData: {
        phrase: "こんにちは",
        definition: "hello; a common daytime greeting",
        pronunciation: "koɴɲitɕiwa",
      },
      preview: { speakers: [], dialogueCount: 0, dialoguePreview: [] },
      warnings: [],
    },
  },
};

export const QARecording = {
  args: {
    toolOutput: {
      preset: "question",
      scriptData: {
        metadata: { title: "Greetings Q&A", version: "1.0" },
        speakers: { narrator: { name: "Narrator", voice: "fable" } },
        dialogue: [
          { speaker: "narrator", text: "How do you say hello in Japanese?" },
        ],
      },
      preview: {
        speakers: [{ id: "narrator", name: "Narrator", voice: "fable" }],
        dialogueCount: 1,
        dialoguePreview: [
          { speaker: "Narrator", text: "How do you say hello in Japanese?" },
        ],
      },
      warnings: ["Only one speaker detected — add a responder for a full Q&A."],
    },
  },
};
