/**
 * RecordingScriptPreview - Displays a preview of an RS3 recording script
 * generated by the create_recording_script chat tool.
 * 
 * Provides buttons to:
 * - Create a new Word (word preset) or File (conversation/question preset) with the scriptData
 * - Open Recording Studio 3 with the generated script
 */

import React, { useState } from 'react';
import {
    Box,
    Typography,
    Button,
    Chip,
    Divider,
    Alert,
} from '@mui/material';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import MicIcon from '@mui/icons-material/Mic';
import RecordVoiceOverIcon from '@mui/icons-material/RecordVoiceOver';
import QuestionAnswerIcon from '@mui/icons-material/QuestionAnswer';
import AbcIcon from '@mui/icons-material/Abc';
import { getAmplifyClient } from '../../utils/amplifyClient';

const PRESET_CONFIG = {
    word: { icon: AbcIcon, label: 'Vocabulary Word', color: 'secondary' },
    conversation: { icon: QuestionAnswerIcon, label: 'Conversation', color: 'primary' },
    question: { icon: RecordVoiceOverIcon, label: 'Q&A Recording', color: 'info' },
};

/**
 * @param {Object} props
 * @param {Object} props.toolOutput - The tool output from create_recording_script
 * @param {Function} props.onOpenStudio - Callback to open RS3 with (preset, scriptData, lockedTracks)
 * @param {string} props.unitId - Current unit ID for model associations
 * @param {string} props.owner - Current user owner string
 * @param {string} props.identityId - Current user identityId
 */
export default function RecordingScriptPreview({ toolOutput, onOpenStudio, unitId, owner, identityId }) {
    const [saving, setSaving] = useState(false);
    const [saved, setSaved] = useState(false);
    const [error, setError] = useState(null);
    const [createdRecord, setCreatedRecord] = useState(null);

    if (!toolOutput || !toolOutput.scriptData) return null;

    const { preset, scriptData, lockedTracks, wordData, fileData, preview, warnings } = toolOutput;
    const config = PRESET_CONFIG[preset] || PRESET_CONFIG.conversation;
    const IconComponent = config.icon;

    const handleCreateRecord = async () => {
        setSaving(true);
        setError(null);

        try {
            const client = getAmplifyClient();

            if (preset === 'word' && wordData) {
                // Create or update a Word record
                if (wordData.existingWordId) {
                    const { data: existing } = await client.models.Word.get({ id: wordData.existingWordId });
                    const { data: updated } = await client.models.Word.update({
                        id: wordData.existingWordId,
                        phrase: wordData.phrase,
                        definition: wordData.definition,
                        pronunciation: wordData.pronunciation || existing?.pronunciation || '',
                        _version: existing?._version,
                    });
                    setCreatedRecord({ type: 'word', id: updated.id, record: updated });
                } else {
                    const { data: newWord } = await client.models.Word.create({
                        phrase: wordData.phrase,
                        definition: wordData.definition,
                        pronunciation: wordData.pronunciation || '',
                        audio: [],
                        identityId: identityId || '',
                    });
                    setCreatedRecord({ type: 'word', id: newWord.id, record: newWord });

                    // Link to unit if available
                    if (unitId && newWord?.id) {
                        await client.models.UnitWord.create({
                            unitId: unitId,
                            wordId: newWord.id,
                        });
                    }
                }
            } else if (fileData) {
                // Create or update a File record containing the scriptData JSON
                const scriptJson = JSON.stringify(scriptData);

                if (fileData.existingFileId) {
                    const { data: existing } = await client.models.File.get({ id: fileData.existingFileId });
                    const { data: updated } = await client.models.File.update({
                        id: fileData.existingFileId,
                        name: fileData.name,
                        description: `RS3 ${preset} script: ${scriptData.metadata.title}`,
                        _version: existing?._version,
                    });
                    setCreatedRecord({ type: 'file', id: updated.id, record: updated });
                } else {
                    const { data: newFile } = await client.models.File.create({
                        name: fileData.name,
                        description: `RS3 ${preset} script: ${scriptData.metadata.title}`,
                        mimeType: 'application/json',
                        level: 'PROTECTED',
                        path: `protected/scripts/${fileData.name}`,
                        owner: owner || '',
                        identityId: identityId || '',
                    });
                    setCreatedRecord({ type: 'file', id: newFile.id, record: newFile });

                    // Link to unit if available
                    if (unitId && newFile?.id) {
                        await client.models.UnitFile.create({
                            unitId: unitId,
                            fileId: newFile.id,
                        });
                    }
                }
            }

            setSaved(true);
        } catch (err) {
            console.error('[RecordingScriptPreview] Error creating record:', err);
            setError(err.message || 'Failed to create record');
        } finally {
            setSaving(false);
        }
    };

    const handleOpenStudio = () => {
        if (onOpenStudio) {
            onOpenStudio(preset, scriptData, lockedTracks);
        }
    };

    return (
        <Box sx={{ width: '100%' }}>
            {/* Header */}
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1.5 }}>
                <IconComponent color={config.color} />
                <Typography variant="subtitle2" sx={{ fontWeight: 600 }}>
                    {scriptData.metadata.title}
                </Typography>
                <Chip label={config.label} size="small" color={config.color} variant="outlined" />
            </Box>

            {/* Warnings */}
            {warnings && warnings.length > 0 && (
                <Alert severity="warning" sx={{ mb: 1, py: 0 }}>
                    {warnings.map((w, i) => <Typography key={i} variant="caption" display="block">{w}</Typography>)}
                </Alert>
            )}

            {/* Word preview */}
            {wordData && (
                <Box sx={{ mb: 1.5, pl: 1, borderLeft: '2px solid', borderColor: 'secondary.main' }}>
                    <Typography variant="caption" color="text.secondary">Phrase:</Typography>
                    <Typography variant="body2" sx={{ fontWeight: 500 }}>{wordData.phrase}</Typography>
                    <Typography variant="caption" color="text.secondary">Definition:</Typography>
                    <Typography variant="body2">{wordData.definition}</Typography>
                    {wordData.pronunciation && (
                        <>
                            <Typography variant="caption" color="text.secondary">Pronunciation:</Typography>
                            <Typography variant="body2">{wordData.pronunciation}</Typography>
                        </>
                    )}
                </Box>
            )}

            {/* Speakers */}
            <Box sx={{ display: 'flex', gap: 0.5, flexWrap: 'wrap', mb: 1 }}>
                {preview?.speakers?.map((s) => (
                    <Chip
                        key={s.id}
                        label={`${s.name} (${s.voice})`}
                        size="small"
                        variant="outlined"
                        icon={<MicIcon sx={{ fontSize: 14 }} />}
                    />
                ))}
            </Box>

            {/* Dialogue preview */}
            <Box sx={{ mb: 1.5 }}>
                <Typography variant="caption" color="text.secondary" sx={{ mb: 0.5, display: 'block' }}>
                    {preview?.dialogueCount} line{preview?.dialogueCount !== 1 ? 's' : ''}:
                </Typography>
                {preview?.dialoguePreview?.map((line, i) => (
                    <Typography key={i} variant="caption" display="block" sx={{ pl: 1, mb: 0.25 }}>
                        <strong>{line.speaker}:</strong> {line.text}
                    </Typography>
                ))}
                {preview?.dialogueCount > 5 && (
                    <Typography variant="caption" color="text.secondary" sx={{ pl: 1 }}>
                        ...and {preview.dialogueCount - 5} more
                    </Typography>
                )}
            </Box>

            <Divider sx={{ my: 1 }} />

            {/* Actions */}
            {error && (
                <Alert severity="error" sx={{ mb: 1, py: 0 }}>
                    <Typography variant="caption">{error}</Typography>
                </Alert>
            )}

            {saved ? (
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                    <CheckCircleIcon color="success" sx={{ fontSize: 18 }} />
                    <Typography variant="caption" color="success.dark">
                        {createdRecord?.type === 'word'
                            ? `Word "${wordData?.phrase}" created`
                            : `Script file "${fileData?.name}" created`
                        }
                    </Typography>
                    {onOpenStudio && (
                        <Button
                            size="small"
                            variant="outlined"
                            startIcon={<MicIcon />}
                            onClick={handleOpenStudio}
                            sx={{ ml: 'auto', textTransform: 'none' }}
                        >
                            Open in Studio
                        </Button>
                    )}
                </Box>
            ) : (
                <Box sx={{ display: 'flex', gap: 1 }}>
                    <Button
                        size="small"
                        variant="contained"
                        onClick={handleCreateRecord}
                        disabled={saving}
                        sx={{ textTransform: 'none' }}
                    >
                        {saving ? 'Creating...' : preset === 'word' ? 'Create Word' : 'Save Script'}
                    </Button>
                    {onOpenStudio && (
                        <Button
                            size="small"
                            variant="outlined"
                            startIcon={<MicIcon />}
                            onClick={handleOpenStudio}
                            disabled={saving}
                            sx={{ textTransform: 'none' }}
                        >
                            Open in Studio
                        </Button>
                    )}
                </Box>
            )}
        </Box>
    );
}
