import getCachedUrl from "./getCachedUrl";

/**
 * Image variant sizes generated by the imageProcess Lambda.
 * Maps variant name to pixel width for srcSet descriptors.
 */
const IMAGE_VARIANTS = {
  small: 320,
  medium: 640,
  large: 1280,
};

/**
 * Build a responsive srcSet string from a file's processed image variants.
 * Resolves S3 presigned URLs for each variant in parallel.
 *
 * @param {string} fileId - The file record ID
 * @param {string} identityId - The owner's Cognito identity ID
 * @returns {Promise<{srcSet: string, sizes: string, fallbackSrc: string} | null>}
 *   Returns null if URLs cannot be resolved.
 */
export async function getResponsiveImageUrls(fileId, identityId) {
  if (!fileId || !identityId) return null;

  const variantPaths = Object.entries(IMAGE_VARIANTS).map(([name, width]) => ({
    name,
    width,
    path: `protected/${identityId}/${fileId}/${name}.webp`,
  }));

  try {
    const results = await Promise.allSettled(
      variantPaths.map(async ({ name, width, path }) => {
        const url = await getCachedUrl(path);
        return { name, width, url };
      }),
    );

    const resolved = results
      .filter((r) => r.status === "fulfilled" && r.value.url)
      .map((r) => r.value);

    if (resolved.length === 0) return null;

    const srcSet = resolved.map((v) => `${v.url} ${v.width}w`).join(", ");

    // Use largest available as fallback src
    const fallbackSrc = resolved[resolved.length - 1].url;

    const sizes = "(max-width: 320px) 320px, (max-width: 640px) 640px, 1280px";

    return { srcSet, sizes, fallbackSrc };
  } catch {
    return null;
  }
}

/**
 * Get the S3 path for a specific image variant.
 * Does NOT resolve the presigned URL — use getCachedUrl on the result.
 *
 * @param {string} fileId
 * @param {string} identityId
 * @param {"thumbnail"|"small"|"medium"|"large"} variant
 * @returns {string}
 */
export function getImageVariantPath(fileId, identityId, variant) {
  return `protected/${identityId}/${fileId}/${variant}.webp`;
}
