#!/usr/bin/env tsx
/**
 * Move translation keys out of a stray/legacy namespace file and into the
 * namespace file the component actually expects, based on the mismatches in
 * translation-verification-report.md (generated by verify-and-add-translations.ts).
 *
 * Unlike scripts/fix-component-namespaces.ts (which edits useTranslations()
 * call sites), this script edits the locale JSON files themselves. Use it
 * when the component's declared namespace is correct and a handful of keys
 * are simply sitting in the wrong/legacy namespace file (e.g. leftovers from
 * before editor.json was split into editor.authoring/.files/.ai/.blocks/.shared).
 *
 * Moves the key across every locale (en, de, es, fr, ja, zh) and the matching
 * .meta.json translator-context file, preserving existing translated values.
 * Never overwrites a value that already exists at the destination path.
 *
 * Usage:
 *   npx tsx scripts/move-mismatched-namespace-keys.ts [--dry-run]
 */

import fs from 'fs';
import path from 'path';

const REPORT_PATH = path.join(process.cwd(), 'translation-verification-report.md');
const LOCALES_DIR = path.join(process.cwd(), 'public/locales');
const LOCALES = ['en', 'de', 'es', 'fr', 'ja', 'zh'];
const DRY_RUN = process.argv.includes('--dry-run');

const KNOWN_NAMESPACES = [
  'auth',
  'common',
  'components',
  'pages',
  'editor',
  'editor.authoring',
  'editor.files',
  'editor.ai',
  'editor.blocks',
  'editor.shared',
  'workbook',
];

interface Mismatch {
  key: string;
  expectedNamespace: string;
  foundInNamespace: string;
}

function resolveNamespace(used: string): { file: string; prefix: string } {
  const candidates = KNOWN_NAMESPACES.filter(
    (ns) => used === ns || used.startsWith(`${ns}.`),
  ).sort((a, b) => b.length - a.length);
  const file = candidates[0] ?? used;
  const prefix = used === file ? '' : used.slice(file.length + 1);
  return { file, prefix };
}

function parseMismatches(): Mismatch[] {
  const content = fs.readFileSync(REPORT_PATH, 'utf-8');
  const regex =
    /### ([^\n]+)\n\n- \*\*Expected namespace\*\*: `([^`]+)`\n- \*\*Found in namespace\*\*: `([^`]+)`/g;
  const mismatches: Mismatch[] = [];
  let m: RegExpExecArray | null;
  while ((m = regex.exec(content)) !== null) {
    mismatches.push({ key: m[1], expectedNamespace: m[2], foundInNamespace: m[3] });
  }
  return mismatches;
}

function getNested(obj: any, keyPath: string): any {
  let current = obj;
  for (const part of keyPath.split('.')) {
    if (!current || typeof current !== 'object' || !(part in current)) return undefined;
    current = current[part];
  }
  return current;
}

function setNested(obj: any, keyPath: string, value: any): void {
  const parts = keyPath.split('.');
  let current = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (!current[parts[i]] || typeof current[parts[i]] !== 'object') current[parts[i]] = {};
    current = current[parts[i]];
  }
  current[parts[parts.length - 1]] = value;
}

function deleteNested(obj: any, keyPath: string): void {
  const parts = keyPath.split('.');
  let current = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (!current || typeof current !== 'object') return;
    current = current[parts[i]];
  }
  if (current && typeof current === 'object') delete current[parts[parts.length - 1]];
}

function sortKeys(obj: any): any {
  if (typeof obj !== 'object' || obj === null || Array.isArray(obj)) return obj;
  const sorted: any = {};
  for (const key of Object.keys(obj).sort()) sorted[key] = sortKeys(obj[key]);
  return sorted;
}

function loadJson(filePath: string): any {
  if (!fs.existsSync(filePath)) return null;
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

function moveOneFile(
  locale: string,
  ns: string,
  destFile: string,
  destPrefix: string,
  moves: Mismatch[],
  suffix: '.json' | '.meta.json',
): { moved: number; conflicts: string[] } {
  const sourcePath = path.join(LOCALES_DIR, locale, `${ns}${suffix}`);
  const destPath = path.join(LOCALES_DIR, locale, `${destFile}${suffix}`);
  const source = loadJson(sourcePath);
  if (!source) return { moved: 0, conflicts: [] };
  const dest = loadJson(destPath) ?? {};

  let moved = 0;
  const conflicts: string[] = [];

  for (const { key } of moves) {
    const fullSourcePath = key;
    const fullDestPath = destPrefix ? `${destPrefix}.${key}` : key;
    const value = getNested(source, fullSourcePath);
    if (value === undefined) continue;

    const existing = getNested(dest, fullDestPath);
    if (existing !== undefined && JSON.stringify(existing) !== JSON.stringify(value)) {
      conflicts.push(`${locale}/${ns}${suffix}:${fullSourcePath} -> ${destFile}${suffix}:${fullDestPath}`);
      continue;
    }

    if (existing === undefined) {
      setNested(dest, fullDestPath, value);
    }
    deleteNested(source, fullSourcePath);
    moved++;
  }

  if (moved > 0 && !DRY_RUN) {
    fs.writeFileSync(sourcePath, JSON.stringify(sortKeys(source), null, 2) + '\n', 'utf-8');
    fs.writeFileSync(destPath, JSON.stringify(sortKeys(dest), null, 2) + '\n', 'utf-8');
  }

  return { moved, conflicts };
}

function main() {
  if (!fs.existsSync(REPORT_PATH)) {
    console.error('❌ translation-verification-report.md not found. Run verify-and-add-translations.ts first.');
    process.exit(1);
  }

  const mismatches = parseMismatches();
  if (mismatches.length === 0) {
    console.log('✅ No namespace mismatches to move.');
    return;
  }

  // Group by (foundInNamespace -> expectedNamespace) pair so we touch each
  // locale/meta file pair exactly once per direction.
  const byDirection = new Map<string, Mismatch[]>();
  for (const m of mismatches) {
    const key = `${m.foundInNamespace}=>${m.expectedNamespace}`;
    if (!byDirection.has(key)) byDirection.set(key, []);
    byDirection.get(key)!.push(m);
  }

  console.log(`🔄 ${mismatches.length} keys across ${byDirection.size} namespace-direction group(s)${DRY_RUN ? ' (dry run)' : ''}\n`);

  let totalMoved = 0;
  const allConflicts: string[] = [];

  for (const [direction, moves] of byDirection.entries()) {
    const [foundNs, expectedNs] = direction.split('=>');
    const { file: destFile, prefix: destPrefix } = resolveNamespace(expectedNs);

    console.log(`📦 ${foundNs} → ${expectedNs} (${moves.length} key${moves.length > 1 ? 's' : ''})`);

    for (const locale of LOCALES) {
      const jsonResult = moveOneFile(locale, foundNs, destFile, destPrefix, moves, '.json');
      const metaResult = moveOneFile(locale, foundNs, destFile, destPrefix, moves, '.meta.json');
      totalMoved += jsonResult.moved;
      allConflicts.push(...jsonResult.conflicts, ...metaResult.conflicts);
      if (jsonResult.moved > 0) {
        console.log(`   ${locale}: moved ${jsonResult.moved}`);
      }
    }
  }

  console.log(`\n✅ Moved ${totalMoved} key/locale entries`);
  if (allConflicts.length > 0) {
    console.log(`\n⚠️  ${allConflicts.length} conflicts skipped (destination already had a different value):`);
    allConflicts.slice(0, 20).forEach((c) => console.log(`   - ${c}`));
    if (allConflicts.length > 20) console.log(`   ... and ${allConflicts.length - 20} more`);
  }
  if (DRY_RUN) console.log('\n(dry run - no files written)');
}

main();
