const theme = {
  blockCursor: 'LanguageEditorTheme__blockCursor',
  characterLimit: 'LanguageEditorTheme__characterLimit',
  code: 'LanguageEditorTheme__code',
  codeHighlight: {
    atrule: 'LanguageEditorTheme__tokenAttr',
    attr: 'LanguageEditorTheme__tokenAttr',
    boolean: 'LanguageEditorTheme__tokenProperty',
    builtin: 'LanguageEditorTheme__tokenSelector',
    cdata: 'LanguageEditorTheme__tokenComment',
    char: 'LanguageEditorTheme__tokenSelector',
    class: 'LanguageEditorTheme__tokenFunction',
    'class-name': 'LanguageEditorTheme__tokenFunction',
    comment: 'LanguageEditorTheme__tokenComment',
    constant: 'LanguageEditorTheme__tokenProperty',
    deleted: 'LanguageEditorTheme__tokenProperty',
    doctype: 'LanguageEditorTheme__tokenComment',
    entity: 'LanguageEditorTheme__tokenOperator',
    function: 'LanguageEditorTheme__tokenFunction',
    important: 'LanguageEditorTheme__tokenVariable',
    inserted: 'LanguageEditorTheme__tokenSelector',
    keyword: 'LanguageEditorTheme__tokenAttr',
    namespace: 'LanguageEditorTheme__tokenVariable',
    number: 'LanguageEditorTheme__tokenProperty',
    operator: 'LanguageEditorTheme__tokenOperator',
    prolog: 'LanguageEditorTheme__tokenComment',
    property: 'LanguageEditorTheme__tokenProperty',
    punctuation: 'LanguageEditorTheme__tokenPunctuation',
    regex: 'LanguageEditorTheme__tokenVariable',
    selector: 'LanguageEditorTheme__tokenSelector',
    string: 'LanguageEditorTheme__tokenSelector',
    symbol: 'LanguageEditorTheme__tokenProperty',
    tag: 'LanguageEditorTheme__tokenProperty',
    url: 'LanguageEditorTheme__tokenOperator',
    variable: 'LanguageEditorTheme__tokenVariable',
  },
  embedBlock: {
    base: 'LanguageEditorTheme__embedBlock',
    focus: 'LanguageEditorTheme__embedBlockFocus',
  },
  hashtag: 'LanguageEditorTheme__hashtag',
  heading: {
    h1: 'LanguageEditorTheme__h1',
    h2: 'LanguageEditorTheme__h2',
    h3: 'LanguageEditorTheme__h3',
    h4: 'LanguageEditorTheme__h4',
    h5: 'LanguageEditorTheme__h5',
    h6: 'LanguageEditorTheme__h6',
  },
  image: 'editor-image',
  indent: 'LanguageEditorTheme__indent',
  inlineImage: 'inline-editor-image',
  layoutContainer: 'LanguageEditorTheme__layoutContaner',
  layoutItem: 'LanguageEditorTheme__layoutItem',
  link: 'LanguageEditorTheme__link',
  list: {
    listitem: 'LanguageEditorTheme__listItem',
    listitemChecked: 'LanguageEditorTheme__listItemChecked',
    listitemUnchecked: 'LanguageEditorTheme__listItemUnchecked',
    nested: {
      listitem: 'LanguageEditorTheme__nestedListItem',
    },
    olDepth: [
      'LanguageEditorTheme__ol1',
      'LanguageEditorTheme__ol2',
      'LanguageEditorTheme__ol3',
      'LanguageEditorTheme__ol4',
      'LanguageEditorTheme__ol5',
    ],
    ul: 'LanguageEditorTheme__ul',
  },
  ltr: 'LanguageEditorTheme__ltr',
  mark: 'LanguageEditorTheme__mark',
  markOverlap: 'LanguageEditorTheme__markOverlap',
  paragraph: 'LanguageEditorTheme__paragraph',
  quote: 'LanguageEditorTheme__quote',
  rtl: 'LanguageEditorTheme__rtl',
  table: 'LanguageEditorTheme__table',
  tableAddColumns: 'LanguageEditorTheme__tableAddColumns',
  tableAddRows: 'LanguageEditorTheme__tableAddRows',
  tableCell: 'LanguageEditorTheme__tableCell',
  tableCellActionButton: 'LanguageEditorTheme__tableCellActionButton',
  tableCellActionButtonContainer:
    'LanguageEditorTheme__tableCellActionButtonContainer',
  tableCellEditing: 'LanguageEditorTheme__tableCellEditing',
  tableCellHeader: 'LanguageEditorTheme__tableCellHeader',
  tableCellPrimarySelected: 'LanguageEditorTheme__tableCellPrimarySelected',
  tableCellResizer: 'LanguageEditorTheme__tableCellResizer',
  tableCellSelected: 'LanguageEditorTheme__tableCellSelected',
  tableCellSortedIndicator: 'LanguageEditorTheme__tableCellSortedIndicator',
  tableResizeRuler: 'LanguageEditorTheme__tableCellResizeRuler',
  tableSelected: 'LanguageEditorTheme__tableSelected',
  tableSelection: 'LanguageEditorTheme__tableSelection',
  text: {
    bold: 'LanguageEditorTheme__textBold',
    code: 'LanguageEditorTheme__textCode',
    italic: 'LanguageEditorTheme__textItalic',
    strikethrough: 'LanguageEditorTheme__textStrikethrough',
    subscript: 'LanguageEditorTheme__textSubscript',
    superscript: 'LanguageEditorTheme__textSuperscript',
    underline: 'LanguageEditorTheme__textUnderline',
    underlineStrikethrough: 'LanguageEditorTheme__textUnderlineStrikethrough',
  },
};

export default theme;