export {
  AUDIO_WAVEFORM_PLAYER_DEFAULTS,
  LEARNER_EXERCISE_WAVEFORM_PRESET,
  STATIC_WAVEFORM_DEFAULTS,
  WAVEFORM_COLOR_FALLBACKS,
  WAVEFORM_CSS_VARIABLES,
  WAVEFORM_DATA_DEFAULTS,
  WAVEFORM_LINE_STYLE,
  WAVEFORM_SEMANTIC_TOKENS,
  resolveWaveformCssColor,
  waveformAmplitudeColor,
  waveformCssColor,
} from "../../../utils/waveformDefaults";
